# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spam < Formula
  desc "Spam binary distribution using homebrew."
  homepage "https://github.com/Steven-Ireland/spam"
  version "1.0.2"
  license "MIT"

  on_macos do
    url "https://github.com/Steven-Ireland/spam/releases/download/v1.0.2/spam_1.0.2_darwin_amd64.tar.gz"
    sha256 "0aabb68db7757e02fe2af457a1f241c031826c87b7d376a1ce2c5bd5c67253b8"

    def install
      bin.install "spam"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Spam
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Steven-Ireland/spam/releases/download/v1.0.2/spam_1.0.2_linux_amd64.tar.gz"
      sha256 "ff058ff0db2fb734edc57fb2a690c1e4dec34b349ed919a1806cfb70cbbc7087"

      def install
        bin.install "spam"
      end
    end
  end
end
